<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="letian-PC" name="AllPullMenu.Pulltive" tests="11" failures="0" timestamp="25 Jun 2015 07:38:06 GMT" time="21.707" errors="1">
  <testcase name="chkBalance" time="0.534" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkOrderApplyCheck" time="0.362" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkTicketCart" time="2.122" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkTicketSale" time="2.123" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkOrderTicket" time="0.656" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkTicketBash" time="2.686" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkOrderRefund" time="0.330" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkTicketGroup" time="2.167" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkTicketFavourite" time="2.108" classname="AllPullMenu.Pulltive"/>
  <testcase name="chkAddUp" time="0.189" classname="AllPullMenu.Pulltive">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at AllPullMenu.Pulltive.chkAddUp(Pulltive.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- chkAddUp -->
  <testcase name="chkOrderBash" time="8.430" classname="AllPullMenu.Pulltive"/>
</testsuite> <!-- AllPullMenu.Pulltive -->
